### PR TITLE
Fix PYTHONTRACEMALLOC env var behavior

### PR DESCRIPTION
**Pull request by carsonip**
Document `tracemalloc.start` `nframe` argument usage as noted in API page.

### CODE REVIEW

**Comment by carsonip** [comment]
I tried to use PYTHONTRACEMALLOC but it didn't work. That's why I assume the env var isn't working. Now I look into the logs and find this:
```
failed to start tracemalloc:
ImportError: No module named _tracemalloc
```
If I start the patched python and `import _tracemalloc`, there is no problem. I guess we just cannot import _tracemalloc when the interpreter starts.

Also, in the [API docs](https://pytracemalloc.readthedocs.io/api.html#differences-between-pytracemalloc-pypi-and-tracemalloc-stdlib), it says:
> There are differences between the third party pytracemalloc module (downloaded from PyPI) and the tracemalloc which is part of the Python standard library:
>    stdlib tracemalloc supports a PYTHONTRACEMALLOC environment variable to start tracing at Python startup.

Therefore I am under the impression that PYTHONTRACEMALLOC never work. I can only get things working with `tracemalloc.start()` with `nframe`. Please let me know if I did anything wrong. If we confirm that PYTHONTRACEMALLOC does not work, we should clearly document it.

**Comment by vstinner** [comment]
> I tried to use PYTHONTRACEMALLOC but it didn't work.

How did you try pytracemalloc? The installation requires to patch the Python source code and compile it manually:
https://pytracemalloc.readthedocs.io/install.html

**Comment by carsonip** [comment]
Yes. I tried with multiple Python versions too. I wrote a blog post [here](http://carsonip.me/posts/debugging-memory-usage-python-tracemalloc/). The part about 2.7.9 and pip is wrong. I'll correct it tonight. But yes, I patched, compiled and installed pytracemalloc with and without virtualenv.

**Comment by vstinner** [comment]
It seems like you used https://github.com/vstinner/pytracemalloc/blob/master/patches/2.7/pep445.patch and this patch checks PYTHONTRACEMALLOC env var, but it's done before initializing the site module. Importing _tracemalloc should work before loading site. You can try using:

```
# -S: don't import site
/opt/tracemalloc/py27/bin/python2.7 -S -c "import tracemalloc"
```

**Comment by vstinner** [comment]
> http://carsonip.me/posts/debugging-memory-usage-python-tracemalloc/

Nice. Did you find your memory leak? :-)

**Comment by carsonip** [comment]
> It seems like you used https://github.com/vstinner/pytracemalloc/blob/master/patches/2.7/pep445.patch and this patch checks PYTHONTRACEMALLOC env var, but it's done before initializing the site module. Importing _tracemalloc should work before loading site. You can try using:
> 
> ```
> # -S: don't import site
> /opt/tracemalloc/py27/bin/python2.7 -S -c "import tracemalloc"
> ```

No, it doesn't work with the `-S`. It works without `-S`. Never worked with PYTHONTRACEMALLOC env var.

Here's the output with `-S`.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tracemalloc.py", line 8, in <module>
    from _tracemalloc import *
ImportError: No module named _tracemalloc
```



> > http://carsonip.me/posts/debugging-memory-usage-python-tracemalloc/
> 
> Nice. Did you find your memory leak? :-)

I wish. I am seeing increasing memory usage in the order of GB in `top` but steady and reasonable objects in order of MB in tracemalloc. Still looking into it.

**Comment by vstinner** [comment]
> No, it doesn't work with the -S. It works without -S. Never worked with PYTHONTRACEMALLOC env var.

Ok, so it's a bug in the patch. The fix is not to change the doc, but fix the patch.

The test on PYTHONTRACEMALLOC env var must be done after initsite(), not before.

**Comment by carsonip** [comment]
> Ok, so it's a bug in the patch. The fix is not to change the doc, but fix the patch.
> 
> The test on PYTHONTRACEMALLOC env var must be done after initsite(), not before.

I'll look into it soon.

**Comment by carsonip** [comment]
Thanks for the tips. Now I've updated the patches, added a testing script for patches, and fixed the documentation. Please let me know your thoughts. Also, is it possible to cut a new release?

**Comment by vstinner** [comment]
Thanks. Fixing the patches is the correct fix, not removing PYTHONTRACEMALLOC from the doc.

Amazing job, it's really annoying to maintain these patches, but it seems like you generated properly these patches! Thanks again.

**Pull request merged**
