### PR TITLE
added pep445 patch for 2.7.15

### PR DESCRIPTION
**Pull request by cloudhan**
This section is intentionally left blank.

### CODE REVIEW

**Comment by vstinner** [comment]
Thanks!

**Comment by vstinner** [comment]
So did tracemalloc work for you to investigate your memory leak?

**Comment by cloudhan** [comment]
yeah, work like a charm!

**Comment by vstinner** [comment]
I released pytracemalloc 1.4 to include your patch. I made a few minor changes (mostly related to doc and release process), nothing impacting the tracemalloc module itself.

**Pull request merged**
